// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeGgGswXsVHWiUXIGhrw5yIvynEMqGKOk',
    appId: '1:943739566893:web:ca6c0bd6b1232c5dba31a4',
    messagingSenderId: '943739566893',
    projectId: 'storytime-4371b',
    authDomain: 'storytime-4371b.firebaseapp.com',
    storageBucket: 'storytime-4371b.firebasestorage.app',
    measurementId: 'G-FFM7N9BMEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn0Oih3bBo_FcfRe6PUbTBnu3dkcfwOkI',
    appId: '1:943739566893:android:22c0a0edb3710e8aba31a4',
    messagingSenderId: '943739566893',
    projectId: 'storytime-4371b',
    storageBucket: 'storytime-4371b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt68j0ODW5336LIp-iEDLwZLlQdp0j0mg',
    appId: '1:943739566893:ios:57cc54768c2c111dba31a4',
    messagingSenderId: '943739566893',
    projectId: 'storytime-4371b',
    storageBucket: 'storytime-4371b.firebasestorage.app',
    iosBundleId: 'com.example.storyajabukanstorypass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt68j0ODW5336LIp-iEDLwZLlQdp0j0mg',
    appId: '1:943739566893:ios:57cc54768c2c111dba31a4',
    messagingSenderId: '943739566893',
    projectId: 'storytime-4371b',
    storageBucket: 'storytime-4371b.firebasestorage.app',
    iosBundleId: 'com.example.storyajabukanstorypass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeGgGswXsVHWiUXIGhrw5yIvynEMqGKOk',
    appId: '1:943739566893:web:e3d07be4327ab726ba31a4',
    messagingSenderId: '943739566893',
    projectId: 'storytime-4371b',
    authDomain: 'storytime-4371b.firebaseapp.com',
    storageBucket: 'storytime-4371b.firebasestorage.app',
    measurementId: 'G-JE2D863T42',
  );
}
